#!/bin/sh
# HOS Snapshot - Automatic System Configuration Tracker

PROJECT_DIR="/mnt/shared_folder"
CONFIG_DIR="$PROJECT_DIR/configs"

echo "HOS Snapshot"
echo "============"

mkdir -p "$CONFIG_DIR"

CONFIG_PATHS="
/etc/network/interfaces
/etc/hostname
/etc/hosts
/etc/apk/repositories
/etc/fstab
/etc/passwd
/etc/group
"

copy_configs() {
    echo "Copying configurations to $CONFIG_DIR..."
    
    for path in $CONFIG_PATHS; do
        if [ -e "$path" ]; then\
            # Create a relative path in Configs
            relative_path=$(echo "$path" | sed 's/^\///')
            target_dir="$CONFIG_DIR/$(dirname "$relative_path")"
            
            # Create a target directory
            mkdir -p "$target_dir"
            
            # Copy a file or directory
            if [ -f "$path" ]; then
                echo "copy file: $path"
                cp "$path" "$target_dir/"
            elif [ -d "$path" ]; then
                echo "copy dir: $path"
                cp -r "$path" "$target_dir/"
            fi
        else
            echo "WARNING: $path does not exist"
        fi
    done
    
    echo "Copying completed!"
}

show_changes() {
    echo "Checking for changes..."
    
    for path in $CONFIG_PATHS; do
        if [ -e "$path" ]; then
            relative_path=$(echo "$path" | sed 's/^\///')
            backup_path="$CONFIG_DIR/$relative_path"
            
            if [ -e "$backup_path" ]; then
                if diff "$path" "$backup_path" >/dev/null 2>&1; then
                    echo "+ $path - no changes"
                else
                    echo "- $path - CHANGED!"
                    diff "$path" "$backup_path" | head -10
                fi
            else
                echo "~ $path - new file"
            fi
        fi
    done
}

while true; do
    echo ""
    echo "Select an action:"
    echo "1 - Copy configurations"
    echo "2 - Show changes(It doesn't work, if you use it, it will finish working)"
    echo "3 - exit"
    echo -n "Your choice [1-3]: "
    
    read choice
    
    case $choice in
        1)
            copy_configs
            ;;
        2)
            # show_changes
            exit 0
            ;;
        3)
            echo "Выход..."
            exit 0
            ;;
        *)
            echo "Неверный выбор!"
            ;;
    esac
done